require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.configs")
require("plugins.cmp")
require("plugins.neotree")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.mason")
require("plugins.dashboard")
require("plugins.lualine")
require("nvim-autopairs").setup {}
